# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ec4dbc9d4d2b25af4b23b95c8cd9ef7fa3e6f008bdb29ab51e2dd5b4e816d84c4b0f7e35a5d79ca652ed79d1f34cea19685fa3db523161076f765ed57ede2b0

test:
  secret_key_base: bedecc5dc7730bd46c18906b13daf7477329218cfcb5d8b2315ce33d75b5bb02cbfd9a9671c32d3aa7c10ca542e1c57578f7299a34d57607ff7631fb5d401c7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
